//
// This file was automatically generated. Please don't edit by hand. Execute Editor command [ Edit > Rendering > Generate Shader Includes ] instead
//

#ifndef AAAADEBUGDISPLAYSETTINGSRENDERING_CS_HLSL
#define AAAADEBUGDISPLAYSETTINGSRENDERING_CS_HLSL
//
// DELTation.AAAARP.Debugging.AAAAGBufferDebugMode:  static fields
//
#define AAAAGBUFFERDEBUGMODE_NONE (0)
#define AAAAGBUFFERDEBUGMODE_DEPTH (1)
#define AAAAGBUFFERDEBUGMODE_ALBEDO (2)
#define AAAAGBUFFERDEBUGMODE_NORMALS (3)
#define AAAAGBUFFERDEBUGMODE_MASKS (4)

//
// DELTation.AAAARP.Debugging.AAAAGPUCullingDebugViewMode:  static fields
//
#define AAAAGPUCULLINGDEBUGVIEWMODE_NONE (0)
#define AAAAGPUCULLINGDEBUGVIEWMODE_FRUSTUM (1)
#define AAAAGPUCULLINGDEBUGVIEWMODE_OCCLUSION (2)
#define AAAAGPUCULLINGDEBUGVIEWMODE_CONE (3)

//
// DELTation.AAAARP.Debugging.AAAALightingDebugMode:  static fields
//
#define AAAALIGHTINGDEBUGMODE_NONE (0)
#define AAAALIGHTINGDEBUGMODE_CLUSTER_Z (1)
#define AAAALIGHTINGDEBUGMODE_DEFERRED_LIGHTS (2)
#define AAAALIGHTINGDEBUGMODE_DIRECTIONAL_LIGHT_CASCADES (3)
#define AAAALIGHTINGDEBUGMODE_AMBIENT_OCCLUSION (4)
#define AAAALIGHTINGDEBUGMODE_BENT_NORMALS (5)

//
// DELTation.AAAARP.Debugging.AAAAVisibilityBufferDebugMode:  static fields
//
#define AAAAVISIBILITYBUFFERDEBUGMODE_NONE (0)
#define AAAAVISIBILITYBUFFERDEBUGMODE_WIREFRAME (1)
#define AAAAVISIBILITYBUFFERDEBUGMODE_BARYCENTRIC_COORDINATES (2)
#define AAAAVISIBILITYBUFFERDEBUGMODE_INSTANCE_ID (3)
#define AAAAVISIBILITYBUFFERDEBUGMODE_MESHLET_ID (4)
#define AAAAVISIBILITYBUFFERDEBUGMODE_INDEX_ID (5)
#define AAAAVISIBILITYBUFFERDEBUGMODE_VERTEX_ID (6)


#endif
