//
// This file was automatically generated. Please don't edit by hand. Execute Editor command [ Edit > Rendering > Generate Shader Includes ] instead
//

#ifndef AAAAVXGICOMMON_CS_HLSL
#define AAAAVXGICOMMON_CS_HLSL
//
// DELTation.AAAARP.Lighting.AAAAVxgiPackedGridChannels:  static fields
//
#define AAAAVXGIPACKEDGRIDCHANNELS_BASE_COLOR_R (0)
#define AAAAVXGIPACKEDGRIDCHANNELS_BASE_COLOR_G (1)
#define AAAAVXGIPACKEDGRIDCHANNELS_BASE_COLOR_B (2)
#define AAAAVXGIPACKEDGRIDCHANNELS_BASE_COLOR_A (3)
#define AAAAVXGIPACKEDGRIDCHANNELS_EMISSIVE_R (4)
#define AAAAVXGIPACKEDGRIDCHANNELS_EMISSIVE_G (5)
#define AAAAVXGIPACKEDGRIDCHANNELS_EMISSIVE_B (6)
#define AAAAVXGIPACKEDGRIDCHANNELS_DIRECT_LIGHT_R (7)
#define AAAAVXGIPACKEDGRIDCHANNELS_DIRECT_LIGHT_G (8)
#define AAAAVXGIPACKEDGRIDCHANNELS_DIRECT_LIGHT_B (9)
#define AAAAVXGIPACKEDGRIDCHANNELS_PACKED_NORMAL_R (10)
#define AAAAVXGIPACKEDGRIDCHANNELS_PACKED_NORMAL_G (11)
#define AAAAVXGIPACKEDGRIDCHANNELS_FRAGMENT_COUNT (12)
#define AAAAVXGIPACKEDGRIDCHANNELS_TOTAL_COUNT (13)


#endif
